name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile.user
        push: true
        tags: jiteshrajoriya/week-18-class:latest  

    - name: Verify Pushed Image
      run: docker pull jiteshrajoriya/week-18-class:latest  

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo docker pull jiteshrajoriya/week-18-class:latest
          sudo docker stop week-18-class || true
          sudo docker rm week-18-class || true
          sudo docker run -d --name week-18-class -p 3005:3000 jiteshrajoriya/week-18-class:latest
